[Interface]
Address = 10.0.3.4/24
PrivateKey = IEGudydovwxasaDV+NgMx8jWLt07Gca3BdyDlH3UX0k=
DNS = 10.0.3.1

[Peer]
PublicKey = 22pH7f4JclotgwuM0sy5W85gLzym5ocobJOVlWzHy3U=
Endpoint = 3.82.89.106:51820
AllowedIPs = 10.0.1.0/24, 10.0.2.0/24, 10.0.3.0/24
PersistentKeepalive = 25
