---
- name: Reload firewalld
  ansible.builtin.command: firewall-cmd --reload
  changed_when: true

- name: Restart exporter stack
  ansible.builtin.command:
    cmd: docker compose up -d --force-recreate
    chdir: /opt/compose/nuc
  changed_when: true

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
