"""authentik_audit: who can sign in, with what MFA, and what happened (Milestone 19, ADR-0024).

Read-only, through Authentik's API as the `home-mcp-audit` service account
(blueprints/home-mcp-audit.yaml), whose role can only view users, groups,
sessions, MFA devices and events. Its token (AUTHENTIK_HOME_MCP_AUDIT_TOKEN)
is generated by the hub deploy and kept in SSM.

Reports:
- active users, admins (superusers, directly or through a group), and
  anyone -- especially an admin -- with no MFA device
- failed logins, suspicious requests and impersonation in the last week,
  with the source addresses
- successful logins per user and how many distinct addresses they came from
- user, group and app/provider changes (who changed what), since a
  surprise there is the clearest sign of a compromised admin
"""

import asyncio
import datetime
import os
from collections import Counter, defaultdict

import httpx

API = os.environ.get("AUTHENTIK_API_URL", "http://authentik-server:9000/api/v3")
TOKEN = os.environ.get("AUTHENTIK_HOME_MCP_AUDIT_TOKEN", "")
if TOKEN == "none":
    TOKEN = ""
SERVICE_ACCOUNT = "home-mcp-audit"
LOOKBACK_DAYS = 7
ALERT_ACTIONS = ["login_failed", "suspicious_request", "impersonation_started", "configuration_error", "policy_exception"]
CHANGE_ACTIONS = ["model_created", "model_updated", "model_deleted", "password_set"]
# Changes to these model types matter; flow/stage/brand churn from
# blueprint applies doesn't.
WATCHED_MODELS = {"user", "group", "role", "token", "application", "oauth2provider", "proxyprovider", "policybinding"}
MAX_EVENT_PAGES = 5


async def _get(client: httpx.AsyncClient, path: str, params=None):
    r = await client.get(f"{API}{path}", params=params, headers={"Authorization": f"Bearer {TOKEN}"}, timeout=15)
    r.raise_for_status()
    return r.json()


async def _events(client: httpx.AsyncClient, actions: list[str], since: datetime.datetime) -> list[dict]:
    """Events of these actions newer than `since`, newest first (paged until older)."""
    params = [("actions", a) for a in actions] + [("ordering", "-created"), ("page_size", "100")]
    out: list[dict] = []
    for page in range(1, MAX_EVENT_PAGES + 1):
        d = await _get(client, "/events/events/", params + [("page", str(page))])
        for ev in d.get("results", []):
            created = datetime.datetime.fromisoformat(ev["created"].replace("Z", "+00:00"))
            if created < since:
                return out
            out.append(ev)
        if not d.get("pagination", {}).get("next"):
            break
    return out


def _who(ev: dict) -> str:
    return (ev.get("user") or {}).get("username") or (ev.get("context") or {}).get("username") or "unknown"


async def authentik_audit() -> str:
    if not TOKEN:
        return "The Authentik audit account isn't set up yet: home-mcp has no API token (it's created on the next hub deploy, ADR-0024)."
    since = datetime.datetime.now(datetime.timezone.utc) - datetime.timedelta(days=LOOKBACK_DAYS)
    async with httpx.AsyncClient() as client:
        try:
            users = (await _get(client, "/core/users/", {"is_active": "true", "page_size": "100"})).get("results", [])
        except httpx.HTTPStatusError as exc:
            return f"Authentik refused the audit account ({exc.response.status_code}); check the home-mcp-audit blueprint applied."
        except httpx.HTTPError as exc:
            return f"I couldn't reach Authentik's API ({type(exc).__name__})."
        people = [u for u in users if u.get("type") in ("internal", "external") and u.get("username") != SERVICE_ACCOUNT]
        devices, alerts, logins, changes = await asyncio.gather(
            asyncio.gather(*(_get(client, "/authenticators/admin/all/", {"user": str(u["pk"])}) for u in people), return_exceptions=True),
            _events(client, ALERT_ACTIONS, since),
            _events(client, ["login"], since),
            _events(client, CHANGE_ACTIONS, since),
            return_exceptions=True,
        )

    flags: list[str] = []
    lines: list[str] = []
    couldnt: list[str] = []

    # Users, admins and MFA.
    admins = []
    no_mfa = []
    for u, devs in zip(people, devices if not isinstance(devices, Exception) else [None] * len(people)):
        is_admin = u.get("is_superuser") or any(g.get("is_superuser") for g in u.get("groups_obj") or [])
        if is_admin:
            admins.append(u["username"])
        if isinstance(devs, Exception) or devs is None:
            couldnt.append(f"MFA devices for {u['username']}")
            continue
        if not [d for d in devs if d.get("confirmed", True)]:
            no_mfa.append(u["username"] + (" (admin)" if is_admin else ""))
    lines.append(
        f"Users: {len(people)} active ({', '.join(sorted(u['username'] for u in people))}); "
        f"admins: {', '.join(sorted(admins)) or 'none'}."
    )
    if no_mfa:
        lines.append("No MFA device: " + ", ".join(sorted(no_mfa)) + ".")
        admin_no_mfa = [n for n in no_mfa if n.endswith("(admin)")]
        if admin_no_mfa:
            flags.append("admin account without MFA: " + ", ".join(n.removesuffix(" (admin)") for n in admin_no_mfa))
    other_accounts = [u["username"] for u in users if u.get("type") not in ("internal", "external") and u.get("username") != SERVICE_ACCOUNT and not u["username"].startswith("ak-outpost")]
    if other_accounts:
        lines.append("Other service accounts: " + ", ".join(sorted(other_accounts)) + ".")

    # Failed logins and other alert events.
    if isinstance(alerts, Exception):
        couldnt.append("security events")
    else:
        by_action = Counter(ev["action"] for ev in alerts)
        if by_action:
            ips = Counter(ev.get("client_ip") or "?" for ev in alerts)
            users_hit = Counter(_who(ev) for ev in alerts if ev["action"] == "login_failed")
            lines.append(
                "This week: " + ", ".join(f"{n} {a.replace('_', ' ')}" for a, n in by_action.most_common())
                + (" (accounts: " + ", ".join(f"{u} {n}" for u, n in users_hit.most_common(4)) + ")" if users_hit else "")
                + "; from " + ", ".join(f"{ip} ({n})" for ip, n in ips.most_common(4)) + "."
            )
            if by_action.get("login_failed", 0) >= 10 or by_action.get("suspicious_request") or by_action.get("impersonation_started"):
                flags.append(", ".join(f"{n} {a.replace('_', ' ')}" for a, n in by_action.most_common()))
        else:
            lines.append("This week: no failed logins or suspicious requests.")

    # Successful logins.
    if isinstance(logins, Exception):
        couldnt.append("login events")
    elif logins:
        per_user: dict[str, set] = defaultdict(set)
        counts = Counter()
        for ev in logins:
            per_user[_who(ev)].add(ev.get("client_ip") or "?")
            counts[_who(ev)] += 1
        lines.append(
            "Logins: " + "; ".join(f"{u} {counts[u]} from {len(ips)} address{'es' if len(ips) != 1 else ''}" for u, ips in sorted(per_user.items())) + "."
        )
        strangers = [u for u in per_user if u not in {p["username"] for p in people}]
        if strangers:
            flags.append("logins by accounts that aren't active people: " + ", ".join(sorted(strangers)))

    # Account and app changes.
    if isinstance(changes, Exception):
        couldnt.append("change events")
    else:
        relevant = []
        for ev in changes:
            model = ((ev.get("context") or {}).get("model") or {})
            kind = (model.get("model_name") or "").lower()
            if ev["action"] == "password_set" or kind in WATCHED_MODELS:
                actor = _who(ev)
                what = model.get("name") or kind or "password"
                relevant.append(f"{ev['action'].replace('model_', '').replace('_', ' ')} {kind or 'user'} {what} by {actor}")
        if relevant:
            lines.append(f"Account/app changes ({len(relevant)}): " + "; ".join(relevant[:6]) + ("; ..." if len(relevant) > 6 else "") + ".")

    head = "Authentik: " + ("; ".join(flags) + "." if flags else "nothing that needs you.")
    out = [head] + lines
    if couldnt:
        out.append("Couldn't check: " + ", ".join(couldnt) + ".")
    return "\n".join(out)
